### ISSUE TITLE
Check consistency of parameters when creating a new project

### ISSUE THREAD

**Issue by martinboers** [PLCnext/PLCnext_CLI#1]
The plcncli build fails on an empty project created with the following parameters:

![image](https://user-images.githubusercontent.com/13133969/95592189-95147100-0a48-11eb-85dc-274f734f8590.png)

(that is a screen shot from Eclipse, but the same parameters can be supplied to the plcncli command line).

There should be some check for parameters sets that are known to cause problems, e.g. when the same name is given for Project namespace and Component, as shown here.

**Comment by mluhmann** [comment]
Fix is planned for the next version.

**Comment by mluhmann** [comment]
Fixed in Toolchain 2022.6
