### ISSUE TITLE
Version 2022.6 cannot install SDK version 2022.6 on Linux

### ISSUE THREAD

**Issue by martinboers** [PLCnext/PLCnext_CLI#14]
To reproduce on a Debian or Ubuntu machine:

- Install plcncli version 2022.0.
- Download the SDK for AXC F 2152 version 2022.6
- Install the SDK using the plcncli  =>  success.
- Uninstall the SDK and delete the installation directory.
- Install plcncli version 2022.6.
- Install the same SDK using the plcncli  =>  fail, with the following message:

![image](https://user-images.githubusercontent.com/13133969/201618324-4374a27c-209e-4b8c-abb5-93f0e0fa579f.png)

**Comment by mluhmann** [comment]
I am not able to reproduce this on a WSL Ubuntu.

**Comment by mluhmann** [comment]
We have now a logfile which helped to identify the issue. Further investigation will be done.

**Comment by mluhmann** [comment]
We did some changes to the SDK installation process and now are not able to reproduce this issue anymore. But we did not find the exact root cause. Please open a new issue if necessary.
