### ISSUE TITLE
VS Code extension lacks to provide proper command line arguments to PLCnCLI

### ISSUE THREAD

**Issue by SetTrend** [PLCnext/PLCnext_CLI#15]
My projects are stored at a repo root location having white space in the path: `"D:\Documents\Visual Studio projects\"`.

The VS Code extension fails to deal with this path in a proper fashion. It's not adding quotes around command line arguments when calling the PLCnCLI command line tool:

![Call to PLCnCLI is lacking quotes](https://user-images.githubusercontent.com/9283914/203338974-b4404a30-c473-4469-9f34-2b4e7eec772a.png)

**Comment by mluhmann** [comment]
Thanks for reporting this issue. It is a defect in our VS plugin and will be fixed in the next version. The release is planned for March 2023.

**Comment by SetTrend** [comment]
Thank a lot, @mluhmann, for taking the time to fix this issue.

Do you want to keep this issue open for reference? Otherwise please close if you feel appropriate. I'm satisfied with your reply.

**Comment by mluhmann** [comment]
Fixed in toolchain release 2023.0
