### ISSUE TITLE
Proposal: Harness PLCnCLI to handle broken SDK installations

### ISSUE THREAD

**Issue by SetTrend** [PLCnext/PLCnext_CLI#16]
Currently, the PLCnext Visual Studio extension is installing SDKs hidden in the background. The process of installing an SDK takes minutes. If Visual Studio is being closed during that period, it's forseeable that the PLCnCLI process spawned by Visual Studio gets killed without further notice.

If that happens, the PLCnCLI SDK configuration gets into an unrecoverable state.

See [this PLCnext forum issue](https://www.plcnext-community.net/forum/#/discussion/comment/11322) for details.

I propose to harness PLCnCLI to automatically restart a previously abandoned installation process by adding a `recover` command to the tool that's checking current installation status and automatically performing all necessary (unfinished) steps.

This new, proposed command, `PLCnCLI RECOVER`, may then be launched by the Visual Studio extension in the background whenever a PLCnext project is opened to make sure the SDK configuration is operating properly.

**Comment by mluhmann** [comment]
This is a bug and will be fixed next version. 
You can work around this by not selecting the option for deleting it from your local drive and delete it manually.

**Comment by mluhmann** [comment]
Fixed with toolchain release 2023.0
