### ISSUE TITLE
SDK installation fails on Linux when $SDKROOT is set

### ISSUE THREAD

**Issue by martinboers** [PLCnext/PLCnext_CLI#8]
On Linux, SDK installation fails when the environment variable $SDKROOT has previously been set (e.g. when previously cross-compiling from the same terminal).

To reproduce on a Linux OS:

- Make sure this directory does not exist: `/opt/pxc/sdk/AXCF2152/2021.0.2`.
- On the command line: `export SDKROOT="/opt/pxc/sdk/AXCF2152/2021.0.2"`
- Attempt to install the SDK for AXC F 2152 FW 2021.0.5 in the directory `/opt/pxc/sdk/AXCF2152/2021.0.5` using `plcncli`.

An error similar to the following appears:

![image](https://user-images.githubusercontent.com/13133969/117630135-2c76a980-b17b-11eb-81c9-b1fa9dc95688.png)

The installation process appears to be using the environment variable $SDKROOT that was set previously.

If the directory given in $SDKROOT does exist, and does contain an SDK, then installing any "new" SDK gives no error, but installs a duplicate of the target that is in the $SDKROOT directory. In that case the problem is quite difficult to diagnose.

**Comment by mluhmann** [comment]
Fix is planned for the next version.

**Comment by twilker** [comment]
I cannot reproduce the defect:
![image](https://user-images.githubusercontent.com/2802526/122026319-5fd7d400-cdca-11eb-86ef-38e13530208f.png)
What version of the toolchain are you using and can you provide me with the log files?

**Comment by martinboers** [comment]
I also now cannot reproduce this with plcncli 21.0.0 LTS (21.0.0.489) and the SDK for AXC F 2152 FW 2021.0.5.
Perhaps I simply had a very messed up shell session.
