### ISSUE TITLE
"generate code" command does not handle arrays with "variable" size

### ISSUE THREAD

**Issue by martinboers** [PLCnext/PLCnext_CLI#9]
for example:

```cpp
#define ARRAY_SIZE
   :
const int arraySize;
  :
//#port
//#attributes(Output|Opc)
int32 myArray1[ARRAY_SIZE];

//#port
//#attributes(Output|Opc)
int32 myArray2[arraySize];
```

The GDS ports `myArray1` and `myArray2` are not created correctly.

I know that this behaviour has been known for a long time, so this issue is only a public record of the requirement.

**Comment by twilker** [comment]
This functionality was fully implemented in the release 22.0
